### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lzucoffee** [Pacific73/Tickets12306#1]
麻烦问一下，这个code要怎么样才能运行呢？在cmd里面吗？我怎么运行都不太对呀，在 idle 也不行。我是小白一个，麻烦了！谢谢！

**Comment by Pacific73** [comment]
在命令行里面运行即可。
python tickets.py beijing shanghai 2016-09-22
格式就像这样~(注意命令行当前目录要和tickets.py的当前目录一致)

**Comment by lzucoffee** [comment]
C:\Users\lzuco\PycharmProjects\Crawler>tickets.py bejing shanghai 2016-09-22
Usage: tickets.py [-gdktz] <fromplace> <toplace> <date>
Arguments:
    <fromplace> place from where you begin this journey
    <toplace> place that you wanna go to
Options:
    -h,--help 甯姪
    -g        楂橀搧
    -d        鍔ㄨ溅
    -k        蹇€?
    -t        鐗瑰揩
    -z        鐩磋揪

C:\Users\lzuco\PycharmProjects\Crawler>    不知道为什么每次都是这样。。。命令行所在目录也对。写上运行python.exe 也不对。
